services:
  dibimbing-dataeng-postgres:
    image: postgres:11
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_CONTAINER_NAME}
    networks:
      - finpro-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/main_pgdata
    volumes:
      # - ../sql:/sql
      # - ./dags/resources/sql:/sql
      - ./dags/resources/sql:/sql
      - ../sql:/sql_external
      - ../data:/data
    ports:
      - ${POSTGRES_PORT}:5432

  dibimbing-dataeng-postgres-replica:
    image: postgres:11
    container_name: ${POSTGRES_REPLICA_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_REPLICA_CONTAINER_NAME}
    networks:
      - finpro-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_REPLICA_PASSWORD}
      - POSTGRES_USER=${POSTGRES_REPLICA_USER}
      - POSTGRES_DB=${POSTGRES_REPLICA_DB}
      - PGDATA=/var/lib/postgresql/data/replica_pgdata
    volumes:
      # - ../sql:/sql
      # - ./dags/resources/sql:/sql
      - ./dags/resources/sql:/sql
      - ../sql:/sql_external
      - ../data:/data
    ports:
      - ${POSTGRES_REPLICA_PORT}:5432

  dibimbing-dataeng-postgres-airflow:
    image: postgres:11
    container_name: ${POSTGRES_AIRFLOW_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_AIRFLOW_CONTAINER_NAME}
    networks:
      - finpro-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_AIRFLOW_PASSWORD}
      - POSTGRES_USER=${POSTGRES_AIRFLOW_USER}
      - POSTGRES_DB=${POSTGRES_AIRFLOW_DB}
      - PGDATA=/var/lib/postgresql/data/airflow_pgdata
    volumes:
      # - ../sql:/sql
      # - ./dags/resources/sql:/sql
      - ./dags/resources/sql:/sql
      - ../sql:/sql_external
      - ../data:/data
    ports:
      - ${POSTGRES_AIRFLOW_PORT}:5432

networks:
  finpro-network:
    driver: bridge
    external: true
